name: "IdentityKeeper Docker image"

on:
  push:

env:
    #create image tag either for master branch or for any other branch
    IMAGE_TAG: ${{ github.ref == 'refs/heads/main' && 'latest' || github.sha }}
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Build Docker image
              run: |
                docker buildx build --platform linux/amd64,linux/arm64 -f ./Dockerfile.Api -t identitykeeper-client . && \
                docker buildx build --platform linux/amd64,linux/arm64 -f ./Dockerfile.Silo -t identitykeeper-server .
            - name: Tag Docker image
              run: |
                docker tag identitykeeper-client ${{ secrets.DOCKER_USERNAME }}/identitykeeper-client:${{ env.IMAGE_TAG }} && \
                docker tag identitykeeper-server ${{ secrets.DOCKER_USERNAME }}/identitykeeper-server:${{ env.IMAGE_TAG }}
            - name: Login to DockerHub
              run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            - name: Push Docker image
              run: |
                docker push ${{ secrets.DOCKER_USERNAME }}/identitykeeper-client:${{ env.IMAGE_TAG }} && \
                docker push ${{ secrets.DOCKER_USERNAME }}/identitykeeper-server:${{ env.IMAGE_TAG }}