name: "IdentityKeeper Docker image"

on:
  push:

env:
    #create image tag either for master branch or for any other branch
    IMAGE_TAG: ${{ github.ref == 'refs/heads/main' && 'latest' || github.sha }}
jobs:
    build-docker-images:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Docker Setup Buildx
              uses: docker/setup-buildx-action@v2.5.0
            - name: Login to DockerHub
              run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            - name: Build & Push Docker image
              run: |
                docker buildx build --platform linux/amd64,linux/arm64 -f ./Dockerfile.Silo -t totosan/identitykeeper-server:${{ env.IMAGE_TAG }} . --push
