
name: init ACA infrastructure

on:
    push:
        
permissions:
    contents: read
    pages: write
    id-token: write
env:
    resourceGroupName: "ORLEANS-ACA"
    location: "westeurope"
    appName: "identitykeeper-app"
    siloName: "identitykeeper-server"
    imageApp: "totosan/identitykeeper-client:latest"
    imageSilo: "totosan/identitykeeper-server:latest"
    registryUsername: "totosan"
    registryPassword: ${{ secrets.DOCKER_PASSWORD }}
    environmentName: "identitykeeperEnv"
    AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}

jobs:
    create-ACA:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Azure Login
              uses: Azure/login@v1.4.6
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            - name: install extension az containerapp
              run: az extension add --name containerapp
            - name: create ACA infrastructure
              run: ./deployment_assets/deployToACA.sh
